# Generated by Django 6.0.3 on 2026-03-30 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "compare_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for sale display",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("single_card", "Single Card"),
                            ("slab", "Graded Slab"),
                            ("sealed", "Sealed Product"),
                            ("protection", "Protection"),
                            ("storage", "Storage"),
                        ],
                        default="single_card",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("near_mint", "Near Mint"),
                            ("excellent", "Excellent"),
                            ("light_played", "Light Played"),
                            ("played", "Played"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Grading score (e.g. 9.5)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "grading_company",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PSA", "PSA"),
                            ("CGC", "CGC"),
                            ("Beckett", "Beckett"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "set_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pokemon set name",
                        max_length=100,
                    ),
                ),
                ("rarity", models.CharField(blank=True, default="", max_length=50)),
                ("card_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "English"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                            ("chinese", "Chinese"),
                        ],
                        default="english",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("stock_quantity", models.PositiveIntegerField(default=1)),
                ("image", models.ImageField(upload_to="products/")),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
